### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by iy-ovo** [iy-ovo/TheatreTicketAlbum#30]
## 各種情報
サービス名：Theater Ticket Album
サービスURL : https://theatreticketalbum.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 投稿
- [x] 一覧
- [ ]  画像加工・合成

## READMEレビュー時から変更した機能
なし

## サービスイメージがわかるようなスクリーンショット等

**レビュー一覧画面**
[![Image from Gyazo](https://i.gyazo.com/f0b7f035e12e68aa5532ce7e795e716d.jpg)](https://gyazo.com/f0b7f035e12e68aa5532ce7e795e716d)

**レビュー作成画面**
[![Image from Gyazo](https://i.gyazo.com/e1aa89d4184658a01552c6909bf79ac2.png)](https://gyazo.com/e1aa89d4184658a01552c6909bf79ac2)

**Comment by kashiwagi-rena** [comment]
ご提出ありがとうございます。

レビュー作成ページができているということは、私も新規レビューできるという認識であってますか？

新規レビューを作成した際に、エラーページに遷移いたしました。
そこから、エラーページしか出てこないようになりました。
確認していただいてもよろしいですか？
<img width="1283" alt="スクリーンショット 2024-08-17 10 22 45" src="https://github.com/user-attachments/assets/45b6a888-294a-41c9-a306-fafe4e75c9a0">

**Comment by iy-ovo** [comment]
確認いただきありがとうございます。

＞レビュー作成ページができているということは、私も新規レビューできるという認識であってますか？
→ご認識の通りです。

＞新規レビューを作成した際に、エラーページに遷移いたしました。
＞そこから、エラーページしか出てこないようになりました。
＞確認していただいてもよろしいですか？
→エラー修正しました。

恐れ入りますがご確認の程、よろしくお願い致します。

**Comment by tarakish** [comment]
LGTMです！
本リリースに向けて引き続き開発頑張ってください。

**Comment by iy-ovo** [comment]
あリがとうございます！
